#!/bin/bash

for k in {1..5..1}
do
j=1
c=2
while ((c <= 256))
do
	for i in {100..1000..100}
	do
		./FWP matrix${j}.txt fwsoutput.txt ${i} ${c} >> fwpnums.csv
		let "j+=1"
	done
	let "c*=2"
	let j=1
done
done
