#!/bin/bash
#/

echo "Please note: This script takes a long time to run!"


# Clear files
> DIJPnums.csv
> BFPnums.csv
> DIJSnums.csv
> BFSnums.csv
> FWPnums.csv
> FWSnums.csv


# Get 5 samples
for k in {1..5..1}
do
	j=1
	c=2
	# 2-256 cores (powers of 2 only)
	while ((c <= 256))
	do
		# 100-1000 size graphs (increment by 100)
		for i in {100..1000..100}
		do
			./DijkstraParallel.o matrix${j}.txt DIJPoutput.txt ${i} ${c} >> DIJPnums.csv
			./BellmanFordParallel.o matrix${j}.txt BFPoutput.txt ${i} ${c} >> BFPnums.csv
			./FloydWarshallParallel.o matrix${j}.txt FWSoutput.txt ${i} ${c} >> FWPnums.csv
			let "j+=1"
		done
		let "c*=2"
		let j=1
	done
done



for k in {1..5..1}
do
	let j=1
	for i in {100..1000..100}
	do
		./DijkstraSequential.o matrix${j}.txt DIJSoutput.txt ${i} >> DIJSnums.csv
		./BellmanFordSequential.o matrix${j}.txt BFSoutput.txt ${i} >> BFSnums.csv
		./FloydWarshallSequential.o matrix${j}.txt FWSoutput.txt ${i} >> FWSnums.csv
		let "j+=1"
	done
done
