#!/bin/bash

echo "Please note, this script takes a VERY long time to run!"

> FWRnums.csv

let "c=2"
let "i=128"
let "j=2"

while ((c <= 256))
do
	let "i=128"
	while ((i <= 2048))
	do
		let "j=2";
		while ((j <= i)) 
		do
			./FloydWarshallRecursiveParallel.o matrix${i}.txt FWRoutput.txt ${i} ${c} ${j} >> FWRnums.csv
			let "j*=2"
		done
		let "i*=2"
	done
	let "c*=2"
done
